### PR TITLE
Add a cleanup service for server side sessions

### PR DESCRIPTION
**Pull request by brockallen**
Fixes: #17

### CODE REVIEW

**Review by seges-tmc — APPROVED** [review]

**Comment by brockallen** [comment]
Docs now added.

**Comment by brockallen** [comment]
@seges-tmc any luck using this so far? any feedback?

**Comment by seges-tmc** [comment]
hi @brockallen 
No I have not had the opportunity to look into it yet.

**Comment by brockallen** [comment]
We'd like to release soon, so if you can have a look that'd be great. We'd love to get any necessary changes in before we release. Thanks.

**Comment by seges-tmc** [comment]
Hi @brockallen 
I tried downloading the nuget version 1.2.0-preview.1. But it does not seem to be in there - at least I cannot find e.g. EnableSessionCleanup on BffOptions.
How do I get a nuget containing the new feature?

**Comment by brockallen** [comment]
Ah... well, I guess you'll have to get it from the nightly builds then: https://docs.duendesoftware.com/identityserver/v6/overview/packaging/#dev-builds

**Comment by seges-tmc** [comment]
Hi @brockallen 
Now I tried it out, and it seems to be working just fine.

**Comment by brockallen** [comment]
Great, thank you!

**Pull request merged**
